### ISSUE TITLE
Question: 

### ISSUE THREAD

**Issue by Weeping-W1llow** [Bumer-32/Redstone-Helper#106]
**Problem**
I can't see all the keybinds in the controls menu it only shows "open calculator"

**Comment by Bumer-32** [comment]
Need more info: what version of the mod? what version of minecraft? maybe some screenshots
Here is the latest version of the mod and everything is working properly:
![image](https://github.com/user-attachments/assets/3616e32e-eeb6-4195-aa89-e6f973d073c4)

**Comment by Weeping-W1llow** [comment]
latest verison 1.20.4

**Comment by Bumer-32** [comment]
in the version for 1.20.4 there is only a calculator)
I was just learning how to create mods back then and that's all I managed to do on this version. everything will work on newer versions of minecraft. if necessary, I can do a backport for this version, but it won't be soon, because lately I don't have much time at all

**Comment by Weeping-W1llow** [comment]
if you have time backporting it would be great but no rush

**Comment by Weeping-W1llow** [comment]
no i need i can update myself
